/**
 * Yapily API
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * OpenAPI spec version: 0.0.154
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.YapilyApi);
  }
}(this, function(expect, YapilyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new YapilyApi.PaymentRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentRequest', function() {
    it('should create an instance of PaymentRequest', function() {
      // uncomment below and update the code to test PaymentRequest
      //var instane = new YapilyApi.PaymentRequest();
      //expect(instance).to.be.a(YapilyApi.PaymentRequest);
    });

    it('should have the property paymentIdempotencyId (base name: "paymentIdempotencyId")', function() {
      // uncomment below and update the code to test the property paymentIdempotencyId
      //var instane = new YapilyApi.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property payerAccountIdentifications (base name: "payerAccountIdentifications")', function() {
      // uncomment below and update the code to test the property payerAccountIdentifications
      //var instane = new YapilyApi.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instane = new YapilyApi.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property reference (base name: "reference")', function() {
      // uncomment below and update the code to test the property reference
      //var instane = new YapilyApi.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property contextType (base name: "contextType")', function() {
      // uncomment below and update the code to test the property contextType
      //var instane = new YapilyApi.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new YapilyApi.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property paymentDateTime (base name: "paymentDateTime")', function() {
      // uncomment below and update the code to test the property paymentDateTime
      //var instane = new YapilyApi.PaymentRequest();
      //expect(instance).to.be();
    });

    it('should have the property payee (base name: "payee")', function() {
      // uncomment below and update the code to test the property payee
      //var instane = new YapilyApi.PaymentRequest();
      //expect(instance).to.be();
    });

  });

}));
