/**
 * Yapily REST API Explorer
 * To access endpoints that require authentication, use your Application <b>key</b> and <b>secret</b> created on the <a href=https://dashboard.yapily.com/ target=_blank>Dashboard</a>
 *
 * OpenAPI spec version: 0.0.2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Institution'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Institution'));
  } else {
    // Browser globals (root is window)
    if (!root.YapilyRestApiExplorer) {
      root.YapilyRestApiExplorer = {};
    }
    root.YapilyRestApiExplorer.YapilyInstitutionsApi = factory(root.YapilyRestApiExplorer.ApiClient, root.YapilyRestApiExplorer.Institution);
  }
}(this, function(ApiClient, Institution) {
  'use strict';

  /**
   * YapilyInstitutions service.
   * @module api/YapilyInstitutionsApi
   * @version 0.0.2
   */

  /**
   * Constructs a new YapilyInstitutionsApi. 
   * @alias module:api/YapilyInstitutionsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getInstitutionsUsingGET operation.
     * @callback module:api/YapilyInstitutionsApi~getInstitutionsUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Institution>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieves the list of Institutions available in Yapily
     * @param {module:api/YapilyInstitutionsApi~getInstitutionsUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Institution>}
     */
    this.getInstitutionsUsingGET = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json;charset=UTF-8'];
      var returnType = [Institution];

      return this.apiClient.callApi(
        '/institutions', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
