/**
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.13.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AccountIdentificationType.
* @enum {}
* @readonly
*/
export default class AccountIdentificationType {
    
        /**
         * value: "SORT_CODE"
         * @const
         */
        "SORT_CODE" = "SORT_CODE";

    
        /**
         * value: "ACCOUNT_NUMBER"
         * @const
         */
        "ACCOUNT_NUMBER" = "ACCOUNT_NUMBER";

    
        /**
         * value: "IBAN"
         * @const
         */
        "IBAN" = "IBAN";

    
        /**
         * value: "BBAN"
         * @const
         */
        "BBAN" = "BBAN";

    
        /**
         * value: "BIC"
         * @const
         */
        "BIC" = "BIC";

    
        /**
         * value: "PAN"
         * @const
         */
        "PAN" = "PAN";

    
        /**
         * value: "MASKED_PAN"
         * @const
         */
        "MASKED_PAN" = "MASKED_PAN";

    
        /**
         * value: "MSISDN"
         * @const
         */
        "MSISDN" = "MSISDN";

    
        /**
         * value: "BSB"
         * @const
         */
        "BSB" = "BSB";

    
        /**
         * value: "NCC"
         * @const
         */
        "NCC" = "NCC";

    
        /**
         * value: "ABA"
         * @const
         */
        "ABA" = "ABA";

    
        /**
         * value: "ABA_WIRE"
         * @const
         */
        "ABA_WIRE" = "ABA_WIRE";

    
        /**
         * value: "ABA_ACH"
         * @const
         */
        "ABA_ACH" = "ABA_ACH";

    
        /**
         * value: "EMAIL"
         * @const
         */
        "EMAIL" = "EMAIL";

    
        /**
         * value: "ROLL_NUMBER"
         * @const
         */
        "ROLL_NUMBER" = "ROLL_NUMBER";

    
        /**
         * value: "BLZ"
         * @const
         */
        "BLZ" = "BLZ";

    
        /**
         * value: "IFS"
         * @const
         */
        "IFS" = "IFS";

    
        /**
         * value: "CLABE"
         * @const
         */
        "CLABE" = "CLABE";

    
        /**
         * value: "CTN"
         * @const
         */
        "CTN" = "CTN";

    
        /**
         * value: "BRANCH_CODE"
         * @const
         */
        "BRANCH_CODE" = "BRANCH_CODE";

    

    /**
    * Returns a <code>AccountIdentificationType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AccountIdentificationType} The enum <code>AccountIdentificationType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

