/**
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.13.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountIdentification from './AccountIdentification';
import Address from './Address';

/**
 * The BeneficiaryPayee model module.
 * @module model/BeneficiaryPayee
 * @version 2.13.1
 */
class BeneficiaryPayee {
    /**
     * Constructs a new <code>BeneficiaryPayee</code>.
     * __Mandatory__. The &#x60;BeneficiaryPayee&#x60; object contains details of the beneficiary [person or business]. You must define this in your payment request along with all of the nested mandatory properties.
     * @alias module:model/BeneficiaryPayee
     * @param accountIdentifications {Array.<module:model/AccountIdentification>} __Mandatory__. The account identifications that identify the `BeneficiaryPayee` bank account.
     */
    constructor(accountIdentifications) { 
        
        BeneficiaryPayee.initialize(this, accountIdentifications);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, accountIdentifications) { 
        obj['accountIdentifications'] = accountIdentifications;
    }

    /**
     * Constructs a <code>BeneficiaryPayee</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BeneficiaryPayee} obj Optional instance to populate.
     * @return {module:model/BeneficiaryPayee} The populated <code>BeneficiaryPayee</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BeneficiaryPayee();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('accountIdentifications')) {
                obj['accountIdentifications'] = ApiClient.convertToType(data['accountIdentifications'], [AccountIdentification]);
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = Address.constructFromObject(data['address']);
            }
        }
        return obj;
    }


}

/**
 * The account holder name of the beneficiary.
 * @member {String} name
 */
BeneficiaryPayee.prototype['name'] = undefined;

/**
 * __Mandatory__. The account identifications that identify the `BeneficiaryPayee` bank account.
 * @member {Array.<module:model/AccountIdentification>} accountIdentifications
 */
BeneficiaryPayee.prototype['accountIdentifications'] = undefined;

/**
 * @member {module:model/Address} address
 */
BeneficiaryPayee.prototype['address'] = undefined;






export default BeneficiaryPayee;

