/**
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.13.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountRequest from './AccountRequest';
import RedirectRequest from './RedirectRequest';
import ScaMethod from './ScaMethod';
import UserCredentials from './UserCredentials';

/**
 * The EmbeddedAccountAuthorisationRequest model module.
 * @module model/EmbeddedAccountAuthorisationRequest
 * @version 2.13.1
 */
class EmbeddedAccountAuthorisationRequest {
    /**
     * Constructs a new <code>EmbeddedAccountAuthorisationRequest</code>.
     * @alias module:model/EmbeddedAccountAuthorisationRequest
     * @param institutionId {String} __Mandatory__. The reference to the `Institution` which identifies which institution the authorisation request is sent to.
     */
    constructor(institutionId) { 
        
        EmbeddedAccountAuthorisationRequest.initialize(this, institutionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, institutionId) { 
        obj['institutionId'] = institutionId;
    }

    /**
     * Constructs a <code>EmbeddedAccountAuthorisationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmbeddedAccountAuthorisationRequest} obj Optional instance to populate.
     * @return {module:model/EmbeddedAccountAuthorisationRequest} The populated <code>EmbeddedAccountAuthorisationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmbeddedAccountAuthorisationRequest();

            if (data.hasOwnProperty('userUuid')) {
                obj['userUuid'] = ApiClient.convertToType(data['userUuid'], 'String');
            }
            if (data.hasOwnProperty('applicationUserId')) {
                obj['applicationUserId'] = ApiClient.convertToType(data['applicationUserId'], 'String');
            }
            if (data.hasOwnProperty('forwardParameters')) {
                obj['forwardParameters'] = ApiClient.convertToType(data['forwardParameters'], ['String']);
            }
            if (data.hasOwnProperty('institutionId')) {
                obj['institutionId'] = ApiClient.convertToType(data['institutionId'], 'String');
            }
            if (data.hasOwnProperty('callback')) {
                obj['callback'] = ApiClient.convertToType(data['callback'], 'String');
            }
            if (data.hasOwnProperty('redirect')) {
                obj['redirect'] = RedirectRequest.constructFromObject(data['redirect']);
            }
            if (data.hasOwnProperty('oneTimeToken')) {
                obj['oneTimeToken'] = ApiClient.convertToType(data['oneTimeToken'], 'Boolean');
            }
            if (data.hasOwnProperty('userCredentials')) {
                obj['userCredentials'] = UserCredentials.constructFromObject(data['userCredentials']);
            }
            if (data.hasOwnProperty('selectedScaMethod')) {
                obj['selectedScaMethod'] = ScaMethod.constructFromObject(data['selectedScaMethod']);
            }
            if (data.hasOwnProperty('scaCode')) {
                obj['scaCode'] = ApiClient.convertToType(data['scaCode'], 'String');
            }
            if (data.hasOwnProperty('accountRequest')) {
                obj['accountRequest'] = AccountRequest.constructFromObject(data['accountRequest']);
            }
        }
        return obj;
    }


}

/**
 * `User` for which the authorisation request was created.
 * @member {String} userUuid
 */
EmbeddedAccountAuthorisationRequest.prototype['userUuid'] = undefined;

/**
 * __Conditional__. The user-friendly reference to the `User` that will authorise the authorisation request. If a `User` with the specified `applicationUserId` exists, it will be used otherwise, a new `User` with the specified `applicationUserId` will be created and used. Either the `userUuid` or `applicationUserId` must be provided.
 * @member {String} applicationUserId
 */
EmbeddedAccountAuthorisationRequest.prototype['applicationUserId'] = undefined;

/**
 * Extra parameters the TPP may want to get forwarded in the callback request after the PSU redirect.
 * @member {Array.<String>} forwardParameters
 */
EmbeddedAccountAuthorisationRequest.prototype['forwardParameters'] = undefined;

/**
 * __Mandatory__. The reference to the `Institution` which identifies which institution the authorisation request is sent to.
 * @member {String} institutionId
 */
EmbeddedAccountAuthorisationRequest.prototype['institutionId'] = undefined;

/**
 * __Optional__. The server to redirect the user to after the user complete the authorisation at the `Institution`. <br><br>See [Using a callback (Optional)](https://docs.yapily.com/) for more information.
 * @member {String} callback
 */
EmbeddedAccountAuthorisationRequest.prototype['callback'] = undefined;

/**
 * @member {module:model/RedirectRequest} redirect
 */
EmbeddedAccountAuthorisationRequest.prototype['redirect'] = undefined;

/**
 * __Conditional__. Used to receive a `oneTimeToken` rather than a `consentToken` at the `callback` for additional security. This can only be used when the `callback` is set. <br><br>See [Using a callback with an OTT (Optional)](https://docs.yapily.com/pages/knowledge/yapily-concepts/callback_url/#using-a-callback-with-an-ott-optional) for more information.
 * @member {Boolean} oneTimeToken
 */
EmbeddedAccountAuthorisationRequest.prototype['oneTimeToken'] = undefined;

/**
 * @member {module:model/UserCredentials} userCredentials
 */
EmbeddedAccountAuthorisationRequest.prototype['userCredentials'] = undefined;

/**
 * @member {module:model/ScaMethod} selectedScaMethod
 */
EmbeddedAccountAuthorisationRequest.prototype['selectedScaMethod'] = undefined;

/**
 * __Conditional__. Used to update the authorisation with the sca code received by the user from the `Institution` using the embedded account authorisation flow.<br><br>This is the penultimate step required in the embedded account authorisation flow to authorise the `Consent`. After sending the sca code, to obtain an authorised consent, the last step is to poll [Get Consent](https://docs.yapily.com/api/reference/#operation/getConsentById) until the `Institution` authorises the request and the `Consent` `status` transitions to `AUTHORIZED`.
 * @member {String} scaCode
 */
EmbeddedAccountAuthorisationRequest.prototype['scaCode'] = undefined;

/**
 * @member {module:model/AccountRequest} accountRequest
 */
EmbeddedAccountAuthorisationRequest.prototype['accountRequest'] = undefined;






export default EmbeddedAccountAuthorisationRequest;

