/**
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.13.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Account from './Account';
import FilterAndSort from './FilterAndSort';

/**
 * The FilteredClientPayloadListAccount model module.
 * @module model/FilteredClientPayloadListAccount
 * @version 2.13.1
 */
class FilteredClientPayloadListAccount {
    /**
     * Constructs a new <code>FilteredClientPayloadListAccount</code>.
     * @alias module:model/FilteredClientPayloadListAccount
     */
    constructor() { 
        
        FilteredClientPayloadListAccount.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FilteredClientPayloadListAccount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FilteredClientPayloadListAccount} obj Optional instance to populate.
     * @return {module:model/FilteredClientPayloadListAccount} The populated <code>FilteredClientPayloadListAccount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FilteredClientPayloadListAccount();

            if (data.hasOwnProperty('apiCall')) {
                obj['apiCall'] = ApiClient.convertToType(data['apiCall'], Object);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [Account]);
            }
            if (data.hasOwnProperty('nextCursorHash')) {
                obj['nextCursorHash'] = ApiClient.convertToType(data['nextCursorHash'], 'String');
            }
            if (data.hasOwnProperty('nextLink')) {
                obj['nextLink'] = ApiClient.convertToType(data['nextLink'], 'String');
            }
            if (data.hasOwnProperty('pagingMap')) {
                obj['pagingMap'] = ApiClient.convertToType(data['pagingMap'], {'String': FilterAndSort});
            }
            if (data.hasOwnProperty('totalCount')) {
                obj['totalCount'] = ApiClient.convertToType(data['totalCount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Object} apiCall
 */
FilteredClientPayloadListAccount.prototype['apiCall'] = undefined;

/**
 * @member {Array.<module:model/Account>} data
 */
FilteredClientPayloadListAccount.prototype['data'] = undefined;

/**
 * @member {String} nextCursorHash
 */
FilteredClientPayloadListAccount.prototype['nextCursorHash'] = undefined;

/**
 * @member {String} nextLink
 */
FilteredClientPayloadListAccount.prototype['nextLink'] = undefined;

/**
 * @member {Object.<String, module:model/FilterAndSort>} pagingMap
 */
FilteredClientPayloadListAccount.prototype['pagingMap'] = undefined;

/**
 * @member {Number} totalCount
 */
FilteredClientPayloadListAccount.prototype['totalCount'] = undefined;






export default FilteredClientPayloadListAccount;

