/**
 * Yapily API
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * The version of the OpenAPI document: 0.0.161
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FrequencyResponse model module.
 * @module model/FrequencyResponse
 * @version 0.0.161
 */
class FrequencyResponse {
    /**
     * Constructs a new <code>FrequencyResponse</code>.
     * @alias module:model/FrequencyResponse
     */
    constructor() { 
        
        FrequencyResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>FrequencyResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FrequencyResponse} obj Optional instance to populate.
     * @return {module:model/FrequencyResponse} The populated <code>FrequencyResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FrequencyResponse();

            if (data.hasOwnProperty('executionDay')) {
                obj['executionDay'] = ApiClient.convertToType(data['executionDay'], 'Number');
            }
            if (data.hasOwnProperty('frequencyType')) {
                obj['frequencyType'] = ApiClient.convertToType(data['frequencyType'], 'String');
            }
            if (data.hasOwnProperty('intervalMonth')) {
                obj['intervalMonth'] = ApiClient.convertToType(data['intervalMonth'], 'Number');
            }
            if (data.hasOwnProperty('intervalWeek')) {
                obj['intervalWeek'] = ApiClient.convertToType(data['intervalWeek'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} executionDay
 */
FrequencyResponse.prototype['executionDay'] = undefined;

/**
 * @member {module:model/FrequencyResponse.FrequencyTypeEnum} frequencyType
 */
FrequencyResponse.prototype['frequencyType'] = undefined;

/**
 * @member {Number} intervalMonth
 */
FrequencyResponse.prototype['intervalMonth'] = undefined;

/**
 * @member {Number} intervalWeek
 */
FrequencyResponse.prototype['intervalWeek'] = undefined;





/**
 * Allowed values for the <code>frequencyType</code> property.
 * @enum {String}
 * @readonly
 */
FrequencyResponse['FrequencyTypeEnum'] = {

    /**
     * value: "DAILY"
     * @const
     */
    "DAILY": "DAILY",

    /**
     * value: "EVERY_WORKING_DAY"
     * @const
     */
    "EVERY_WORKING_DAY": "EVERY_WORKING_DAY",

    /**
     * value: "CALENDAR_DAY"
     * @const
     */
    "CALENDAR_DAY": "CALENDAR_DAY",

    /**
     * value: "WEEKLY"
     * @const
     */
    "WEEKLY": "WEEKLY",

    /**
     * value: "EVERY_TWO_WEEKS"
     * @const
     */
    "EVERY_TWO_WEEKS": "EVERY_TWO_WEEKS",

    /**
     * value: "MONTHLY"
     * @const
     */
    "MONTHLY": "MONTHLY",

    /**
     * value: "EVERY_TWO_MONTHS"
     * @const
     */
    "EVERY_TWO_MONTHS": "EVERY_TWO_MONTHS",

    /**
     * value: "QUARTERLY"
     * @const
     */
    "QUARTERLY": "QUARTERLY",

    /**
     * value: "SEMIANNUAL"
     * @const
     */
    "SEMIANNUAL": "SEMIANNUAL",

    /**
     * value: "ANNUAL"
     * @const
     */
    "ANNUAL": "ANNUAL"
};



export default FrequencyResponse;

