/**
 * Yapily API
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * The version of the OpenAPI document: 0.0.161
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MultiAuthorisation model module.
 * @module model/MultiAuthorisation
 * @version 0.0.161
 */
class MultiAuthorisation {
    /**
     * Constructs a new <code>MultiAuthorisation</code>.
     * @alias module:model/MultiAuthorisation
     */
    constructor() { 
        
        MultiAuthorisation.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MultiAuthorisation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MultiAuthorisation} obj Optional instance to populate.
     * @return {module:model/MultiAuthorisation} The populated <code>MultiAuthorisation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MultiAuthorisation();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('numberOfAuthorisationRequired')) {
                obj['numberOfAuthorisationRequired'] = ApiClient.convertToType(data['numberOfAuthorisationRequired'], 'Number');
            }
            if (data.hasOwnProperty('numberOfAuthorisationReceived')) {
                obj['numberOfAuthorisationReceived'] = ApiClient.convertToType(data['numberOfAuthorisationReceived'], 'Number');
            }
            if (data.hasOwnProperty('lastUpdatedDateTime')) {
                obj['lastUpdatedDateTime'] = ApiClient.convertToType(data['lastUpdatedDateTime'], 'Date');
            }
            if (data.hasOwnProperty('expirationDateTime')) {
                obj['expirationDateTime'] = ApiClient.convertToType(data['expirationDateTime'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {String} status
 */
MultiAuthorisation.prototype['status'] = undefined;

/**
 * @member {Number} numberOfAuthorisationRequired
 */
MultiAuthorisation.prototype['numberOfAuthorisationRequired'] = undefined;

/**
 * @member {Number} numberOfAuthorisationReceived
 */
MultiAuthorisation.prototype['numberOfAuthorisationReceived'] = undefined;

/**
 * @member {Date} lastUpdatedDateTime
 */
MultiAuthorisation.prototype['lastUpdatedDateTime'] = undefined;

/**
 * @member {Date} expirationDateTime
 */
MultiAuthorisation.prototype['expirationDateTime'] = undefined;






export default MultiAuthorisation;

