/**
 * Yapily API
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * The version of the OpenAPI document: 0.0.161
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NewApplicationUser model module.
 * @module model/NewApplicationUser
 * @version 0.0.161
 */
class NewApplicationUser {
    /**
     * Constructs a new <code>NewApplicationUser</code>.
     * @alias module:model/NewApplicationUser
     */
    constructor() { 
        
        NewApplicationUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NewApplicationUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NewApplicationUser} obj Optional instance to populate.
     * @return {module:model/NewApplicationUser} The populated <code>NewApplicationUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NewApplicationUser();

            if (data.hasOwnProperty('applicationUserId')) {
                obj['applicationUserId'] = ApiClient.convertToType(data['applicationUserId'], 'String');
            }
            if (data.hasOwnProperty('referenceId')) {
                obj['referenceId'] = ApiClient.convertToType(data['referenceId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} applicationUserId
 */
NewApplicationUser.prototype['applicationUserId'] = undefined;

/**
 * @member {String} referenceId
 */
NewApplicationUser.prototype['referenceId'] = undefined;






export default NewApplicationUser;

