/**
 * Yapily API
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * The version of the OpenAPI document: 0.0.160
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Next model module.
 * @module model/Next
 * @version 0.0.161
 */
class Next {
    /**
     * Constructs a new <code>Next</code>.
     * @alias module:model/Next
     */
    constructor() { 
        
        Next.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Next</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Next} obj Optional instance to populate.
     * @return {module:model/Next} The populated <code>Next</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Next();

            if (data.hasOwnProperty('before')) {
                obj['before'] = ApiClient.convertToType(data['before'], 'Date');
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} before
 */
Next.prototype['before'] = undefined;

/**
 * @member {Date} from
 */
Next.prototype['from'] = undefined;






export default Next;

