/**
 * Yapily API
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * The version of the OpenAPI document: 0.0.161
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OverdraftOverdraftFeeChargeCap from './OverdraftOverdraftFeeChargeCap';
import OverdraftOverdraftFeeChargeDetail from './OverdraftOverdraftFeeChargeDetail';

/**
 * The OverdraftOverdraftFeesCharges model module.
 * @module model/OverdraftOverdraftFeesCharges
 * @version 0.0.161
 */
class OverdraftOverdraftFeesCharges {
    /**
     * Constructs a new <code>OverdraftOverdraftFeesCharges</code>.
     * Overdraft fees and charges
     * @alias module:model/OverdraftOverdraftFeesCharges
     */
    constructor() { 
        
        OverdraftOverdraftFeesCharges.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OverdraftOverdraftFeesCharges</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OverdraftOverdraftFeesCharges} obj Optional instance to populate.
     * @return {module:model/OverdraftOverdraftFeesCharges} The populated <code>OverdraftOverdraftFeesCharges</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OverdraftOverdraftFeesCharges();

            if (data.hasOwnProperty('OverdraftFeeChargeCap')) {
                obj['OverdraftFeeChargeCap'] = ApiClient.convertToType(data['OverdraftFeeChargeCap'], [OverdraftOverdraftFeeChargeCap]);
            }
            if (data.hasOwnProperty('OverdraftFeeChargeDetail')) {
                obj['OverdraftFeeChargeDetail'] = ApiClient.convertToType(data['OverdraftFeeChargeDetail'], [OverdraftOverdraftFeeChargeDetail]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/OverdraftOverdraftFeeChargeCap>} OverdraftFeeChargeCap
 */
OverdraftOverdraftFeesCharges.prototype['OverdraftFeeChargeCap'] = undefined;

/**
 * @member {Array.<module:model/OverdraftOverdraftFeeChargeDetail>} OverdraftFeeChargeDetail
 */
OverdraftOverdraftFeesCharges.prototype['OverdraftFeeChargeDetail'] = undefined;






export default OverdraftOverdraftFeesCharges;

