/**
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.13.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ConsentDeleteResponse from './ConsentDeleteResponse';
import DeleteStatusEnum from './DeleteStatusEnum';

/**
 * The UserDeleteResponse model module.
 * @module model/UserDeleteResponse
 * @version 2.13.1
 */
class UserDeleteResponse {
    /**
     * Constructs a new <code>UserDeleteResponse</code>.
     * @alias module:model/UserDeleteResponse
     */
    constructor() { 
        
        UserDeleteResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserDeleteResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserDeleteResponse} obj Optional instance to populate.
     * @return {module:model/UserDeleteResponse} The populated <code>UserDeleteResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserDeleteResponse();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('deleteStatus')) {
                obj['deleteStatus'] = DeleteStatusEnum.constructFromObject(data['deleteStatus']);
            }
            if (data.hasOwnProperty('creationDate')) {
                obj['creationDate'] = ApiClient.convertToType(data['creationDate'], 'Date');
            }
            if (data.hasOwnProperty('userConsents')) {
                obj['userConsents'] = ApiClient.convertToType(data['userConsents'], [ConsentDeleteResponse]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} id
 */
UserDeleteResponse.prototype['id'] = undefined;

/**
 * @member {module:model/DeleteStatusEnum} deleteStatus
 */
UserDeleteResponse.prototype['deleteStatus'] = undefined;

/**
 * @member {Date} creationDate
 */
UserDeleteResponse.prototype['creationDate'] = undefined;

/**
 * @member {Array.<module:model/ConsentDeleteResponse>} userConsents
 */
UserDeleteResponse.prototype['userConsents'] = undefined;






export default UserDeleteResponse;

