/**
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.13.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserCredentials model module.
 * @module model/UserCredentials
 * @version 2.13.1
 */
class UserCredentials {
    /**
     * Constructs a new <code>UserCredentials</code>.
     * __Conditional__. Used to capture the user&#39;s credentials to allow them to login to an &#x60;Institution&#x60; that uses the embedded account authorisation flow. &lt;br&gt;&lt;br&gt;This is the first step required in the embedded account authorisation flow to authorise the &#x60;Consent&#x60;.
     * @alias module:model/UserCredentials
     * @param id {String} __Mandatory__. The login id for the user for a particular `Institution`.
     * @param password {String} __Mandatory__. The password of the user to login to a particular `Institution`.
     */
    constructor(id, password) { 
        
        UserCredentials.initialize(this, id, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, password) { 
        obj['id'] = id;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>UserCredentials</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserCredentials} obj Optional instance to populate.
     * @return {module:model/UserCredentials} The populated <code>UserCredentials</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserCredentials();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('corporateId')) {
                obj['corporateId'] = ApiClient.convertToType(data['corporateId'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * __Mandatory__. The login id for the user for a particular `Institution`.
 * @member {String} id
 */
UserCredentials.prototype['id'] = undefined;

/**
 * __Conditional__. The corporate login for the user for a particular corporate `Institution`.
 * @member {String} corporateId
 */
UserCredentials.prototype['corporateId'] = undefined;

/**
 * __Mandatory__. The password of the user to login to a particular `Institution`.
 * @member {String} password
 */
UserCredentials.prototype['password'] = undefined;






export default UserCredentials;

