/**
 * Yapily API
 * The Yapily API enables connections between your application and users' banks. For more information check out our [documentation](https://docs.yapily.com/).<br><br>In particular, make sure to view our [Getting Started](https://docs.yapily.com/pages/home/getting-started/) steps if this is your first time here.<br><br>While testing the API, our list of [sandbox credentials](https://docs.yapily.com/pages/key-concepts/sandbox-credentials/) maybe useful.
 *
 * The version of the OpenAPI document: 2.13.1
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountIdentification from './AccountIdentification';

/**
 * The VirtualAccountBankAccount model module.
 * @module model/VirtualAccountBankAccount
 * @version 2.13.1
 */
class VirtualAccountBankAccount {
    /**
     * Constructs a new <code>VirtualAccountBankAccount</code>.
     * @alias module:model/VirtualAccountBankAccount
     */
    constructor() { 
        
        VirtualAccountBankAccount.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>VirtualAccountBankAccount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/VirtualAccountBankAccount} obj Optional instance to populate.
     * @return {module:model/VirtualAccountBankAccount} The populated <code>VirtualAccountBankAccount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VirtualAccountBankAccount();

            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('bankName')) {
                obj['bankName'] = ApiClient.convertToType(data['bankName'], 'String');
            }
            if (data.hasOwnProperty('bankAddress')) {
                obj['bankAddress'] = ApiClient.convertToType(data['bankAddress'], 'String');
            }
            if (data.hasOwnProperty('bankCountry')) {
                obj['bankCountry'] = ApiClient.convertToType(data['bankCountry'], 'String');
            }
            if (data.hasOwnProperty('accountIdentifications')) {
                obj['accountIdentifications'] = ApiClient.convertToType(data['accountIdentifications'], [AccountIdentification]);
            }
            if (data.hasOwnProperty('payInReference')) {
                obj['payInReference'] = ApiClient.convertToType(data['payInReference'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Three-letter ISO 4217 currency code
 * @member {String} currency
 */
VirtualAccountBankAccount.prototype['currency'] = undefined;

/**
 * @member {String} bankName
 */
VirtualAccountBankAccount.prototype['bankName'] = undefined;

/**
 * @member {String} bankAddress
 */
VirtualAccountBankAccount.prototype['bankAddress'] = undefined;

/**
 * Two-letter ISO 3166 country code
 * @member {String} bankCountry
 */
VirtualAccountBankAccount.prototype['bankCountry'] = undefined;

/**
 * The account identifications that identify the Beneficiary bank account.
 * @member {Array.<module:model/AccountIdentification>} accountIdentifications
 */
VirtualAccountBankAccount.prototype['accountIdentifications'] = undefined;

/**
 * Reference required for paying into the account. When no reference is provided, then one is not required to pay into the acount.
 * @member {String} payInReference
 */
VirtualAccountBankAccount.prototype['payInReference'] = undefined;






export default VirtualAccountBankAccount;

