/**
 * Yapily API
 * To access endpoints that require authentication, use your application key and secret created in the Dashboard (https://dashboard.yapily.com)
 *
 * The version of the OpenAPI document: 0.0.160
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The YapilyAccessToken model module.
 * @module model/YapilyAccessToken
 * @version 0.0.161
 */
class YapilyAccessToken {
    /**
     * Constructs a new <code>YapilyAccessToken</code>.
     * @alias module:model/YapilyAccessToken
     */
    constructor() { 
        
        YapilyAccessToken.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>YapilyAccessToken</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/YapilyAccessToken} obj Optional instance to populate.
     * @return {module:model/YapilyAccessToken} The populated <code>YapilyAccessToken</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new YapilyAccessToken();

            if (data.hasOwnProperty('access_token')) {
                obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
            }
            if (data.hasOwnProperty('expires_in')) {
                obj['expires_in'] = ApiClient.convertToType(data['expires_in'], 'Number');
            }
            if (data.hasOwnProperty('jti')) {
                obj['jti'] = ApiClient.convertToType(data['jti'], 'String');
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = ApiClient.convertToType(data['scope'], 'String');
            }
            if (data.hasOwnProperty('token_type')) {
                obj['token_type'] = ApiClient.convertToType(data['token_type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} access_token
 */
YapilyAccessToken.prototype['access_token'] = undefined;

/**
 * @member {Number} expires_in
 */
YapilyAccessToken.prototype['expires_in'] = undefined;

/**
 * @member {String} jti
 */
YapilyAccessToken.prototype['jti'] = undefined;

/**
 * @member {String} scope
 */
YapilyAccessToken.prototype['scope'] = undefined;

/**
 * @member {String} token_type
 */
YapilyAccessToken.prototype['token_type'] = undefined;






export default YapilyAccessToken;

